site_name: Benji Docs
theme: 
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    primary: custom
    accent: custom
    background: custom
extra_css:
  - stylesheets/extra.css    
