site_name: Benji Docs
theme: 
  name: material
  language: en
  plugins:
   - search
  features:
    - toc.integrate
    - navigation.top
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - search.suggest
    - navigation.footer
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - admonition
  palette:
    primary: custom
    accent: custom
    background: custom
extra_css:
  - stylesheets/extra.css